//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classification { get; set; }
        public virtual DbSet<DataSet> DataSet { get; set; }
        public virtual DbSet<Label> Label { get; set; }
        public virtual DbSet<Mapping> Mapping { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<ModelType> ModelType { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestDataSet> TestDataSet { get; set; }
        public virtual DbSet<TestLabel> TestLabel { get; set; }
        public virtual DbSet<TestResult> TestResult { get; set; }
    }
}
