//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResult()
        {
            this.Classification = new HashSet<Classification>();
        }
    
        public int Id { get; set; }
        public int TestId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classification> Classification { get; set; }
        public virtual Model Model { get; set; }
        public virtual Test Test { get; set; }
    }
}
